spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/hillel
      username: ${pg_user}
      password: ${pg_password}

logging:
  level:
    root: info
  file:
    name: Java_Pro_dom_35.log

